# Generated by Django 4.2.10 on 2024-02-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendskill',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='frontendskill',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
