# Generated by Django 4.2.10 on 2024-04-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_backendskill_level_alter_frontendskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='cv',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
